//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_Cloud.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Word_Cloud.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aan
        ///al
        ///alleen
        ///alles
        ///als
        ///ben
        ///bent
        ///bij
        ///daar
        ///dan
        ///dat
        ///de
        ///denk
        ///deze
        ///die
        ///dit
        ///doe
        ///doen
        ///door
        ///dus
        ///echt
        ///een
        ///eens
        ///en
        ///er
        ///even
        ///ga
        ///gaan
        ///gaat
        ///geen
        ///goed
        ///haar
        ///had
        ///heb
        ///hebben
        ///hebt
        ///heeft
        ///hem
        ///het
        ///hier
        ///hij
        ///hoe
        ///iets
        ///ik
        ///in
        ///is
        ///ja
        ///je
        ///jij
        ///jou
        ///jullie
        ///kan
        ///kom
        ///kunnen
        ///laat
        ///maar
        ///man
        ///me
        ///mee
        ///meer
        ///met
        ///mij
        ///mijn
        ///moet
        ///moeten
        ///naar
        ///nee
        ///niet
        ///nog
        ///nooit
        ///nu
        ///of
        ///oke
        ///om
        ///ons
        ///ook
        ///op
        ///over
        ///te
        ///toch
        ///u
        ///uit
        ///van
        ///voor
        ///waar
        ///waarom
        ///was
        ///wat
        ///we
        ///weet
        ///weg
        ///wel
        ///wie
        ///wil
        ///zal
        ///ze
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dutch100 {
            get {
                return ResourceManager.GetString("dutch100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///be
        ///to
        ///of
        ///and
        ///a
        ///in
        ///that
        ///have
        ///I
        ///it
        ///for
        ///not
        ///on
        ///with
        ///he
        ///as
        ///you
        ///do
        ///at
        ///this
        ///but
        ///his
        ///by
        ///from
        ///they
        ///we
        ///say
        ///her
        ///she
        ///or
        ///an
        ///will
        ///my
        ///one
        ///all
        ///would
        ///there
        ///their
        ///what
        ///so
        ///up
        ///out
        ///if
        ///about
        ///who
        ///get
        ///which
        ///go
        ///me
        ///when
        ///make
        ///can
        ///like
        ///time
        ///no
        ///just
        ///him
        ///know
        ///take
        ///people
        ///into
        ///year
        ///your
        ///good
        ///some
        ///could
        ///them
        ///see
        ///other
        ///than
        ///then
        ///now
        ///look
        ///only
        ///come
        ///its
        ///over
        ///think
        ///also
        ///back
        ///after
        ///use
        ///two
        ///how
        ///our
        ///work
        ///first
        ///well
        ///way
        ///even
        ///new
        ///want
        ///because
        ///any
        ///th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string english100 {
            get {
                return ResourceManager.GetString("english100", resourceCulture);
            }
        }
    }
}
